### PR TITLE
sanitize inputs to prevent XSS

### PR DESCRIPTION
**Pull request by itzunagi**
- update to Swift version 3.1.1
- sanitize inputs to prevent XSS
- add Germany endpoint to readme

### CODE REVIEW

**Comment by rolivieri** [comment]
@degrim Just wondering if you ran into a specific problem when adding visitors. If the payload is not a valid JSON payload, then the first guard in that method (`guard let jsonPayload = request.body?.asJSON else...` should take care of it. I could be missing how a cross site scripting attack could occur in this scenario. 

It could be a valid case that someone chooses to use "us>them" as the value for the name property in the JSON payload… if we sanitize that payload, then the value for the name in the JSON document becomes "us&gtthem", which is not what the user of the demo app is expecting. Did I miss something?

**Comment by itzunagi** [comment]
@rolivieri When displayed, the `&gt;` becomes `>`.  If it is not converted to this, the `>` is interpreted as a closing bracket for an HTML tag.  For example, entering `<script type="text/javascript>alert("wooohooo! I'm doing bad stuff!");</script>` results in some javascript code executing every time the page is viewed by other users.  That's what we want to avoid here.

**Comment by rolivieri** [comment]
@degrim I may still be missing something... A JSON document can contain anything (even HTML or JS code) as long as it is valid JSON. I am not sure we should have code [in the demo app] to tamper with the uploaded JSON document. Instead, I am thinking it should be saved with the same elements it was uploaded with.

Here a few questions/comments to make sure I understood correctly the code changes at https://github.com/degrim/get-started-swift/blob/fb45ce097a793280d871f42896086cb06e79f3ab/Sources/Controller.swift:

1) Say a valid JSON document is received from the client by this demo app and say the JSON document has a `name` field, which (for whatever reason the user had) its value is: `5>4&4<10`. 

2) Say that we now "sanitize" that JSON document… doing so with the `sanitizeInput()` function will then result in this as the value for `name`: `5&gt;4&amp;4&lt;10`, correct?

3) Then the document that gets stored in the database is this:

```
{ name: "5&gt;4&amp;4&lt;10" }
```

4) If the user then uses curl, a web based REST client (e.g. Postman), or just a program that makes a REST invocation to retrieve that document from the Cloudant database, then they will get this:

```
{ name: "5&gt;4&amp;4&lt;10" }
```

5) That's not the expected outcome since the JSON document the user uploaded is:

```
{ name: "5>4&4<10" }
```
Is the above description accurate of the outcome we would get if we sanitize the JSON document?

**Comment by opiethehokie** [comment]
I think I'm in agreement with @rolivieri here, it doesn't matter what's in the DB and as a consumer of the API the client-side code just needs to worry about displaying it properly.

If we were checking for an injection attack then it would have to be in the server-side code since someone could use the UI or call the API directly.

**Comment by itzunagi** [comment]
@rolivieri @opiethehokie I updated the code to sanitize when reading from the database instead of when writing to it.  The uploaded data will be stored as-is in the database now and only sanitized when displayed using our UI.

**Comment by rolivieri** [comment]
@degrim Though moving the code from the `addVisitors()` method to the `getVisitors()` method ensures the JSON document is stored with the expected content in the cloudant database… it still does not address the issue that the user will get a tampered document back when invoking the  `getVisitors()` method. Here’s the scenario:

1) A valid JSON document is received and stored in the database. And for whatever reason the user had, the value for the name property is: `5>4&4<10`.

2) “Sanitizing” that JSON document in the `getVisitors()` method would then have the following unexpected effect: If the user uses curl, a web based REST client (e.g. Postman), or just a program that makes a REST invocation to retrieve that document (i.e. invokes the `getVisitors()` method), then they will get this:
```
{ name: "5&gt;4&amp;4&lt;10" }
```
That's not the expected outcome since the JSON document the user uploaded is:
```
{ name: "5>4&4<10" }
```
I still don’t see the need to tamper with the JSON document. If a client of this server (demo app) is to render the document in an HTML page, then it would be up to that client to take any measures to ensure against xss… but not here on the server side. Any types of clients can access the `getVisitors()` method and these clients should get the exact same document as it was stored in the database.

**Comment by rolivieri** [comment]
@degrim Looks good to me, thanks for moving that logic to the client. I will let @rvennam merge the changes (maybe you want to merge first into develop).

**Review by opiethehokie — APPROVED** [review]

**Pull request merged**
